### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by rohitkapali** [paulvl/backup#12]

**Comment by paulvl** [comment]
Please add more information like:
- laravel version
- OS
- backup version
- and any error message you can see

**Comment by rohitkapali** [comment]
Thank you for replying sir, but I have solved the issue. The issue was that I had not specified the location of the mysqldump.exe file in the config/backup.php properly or rather just gave the path for the file instead of specifying the file name itself. I did not know that I had to do that because I did not find that in the description. I would be nice to specify that in the description(Quick Installation) so that future users wont get confused.
It's working perfectly fine for me right now. Thanks for creating this. Helped me big time. Thank you again sir.

**Comment by paulvl** [comment]
@rohitkapali yes you are right the option is there in the config file indications but not in the docs, I'll add it. You're welcome =)
