### ISSUE TITLE
Call backup command from Route

### ISSUE THREAD

**Issue by knightazura** [paulvl/backup#17]
Hi Paul, first thanks for this great package!

I've tested using terminal and everything works well.
But how can I call the `backup:mysql-dump` command in route / controller?
It's always say "database cannot dumped".

Thanks

**Comment by donksly** [comment]
check the config/backup.php and ensure your mysqldump_path is correct, i had to change mine: 
from: 'mysqldump_path' => 'mysqldump'
       
to: 'mysqldump_path' => 'C:\xampp\mysql\bin\mysqldump'
