### ISSUE TITLE
Erorr whe try restore DB

### ISSUE THREAD

**Issue by AlexMcowkin** [paulvl/backup#19]
Hi!
Thank you for extension.

Look. I try create restoring database from site. I created view. and when I press button 'restore' I need that my DB was restored.

via console works fine =)

In controller I try such command:
`\Artisan::call('backup:mysql-restore --yes --filename='.$file);`

And I see error:

> Command "backup:mysql-restore --yes --filename=advisordev_db_20171226145541.sql" is not defined. Did you mean one of these? backup:mysql-dump backup:mysql-restore

What is the problem? Can you help me?

**Comment by paulvl** [comment]
@AlexMcowkin need to call the command properly from the code. See #21
