### ISSUE TITLE
php artisan mysql-dump custom_file How to Execute From Code

### ISSUE THREAD

**Issue by MadHack25** [paulvl/backup#21]
in My Function Code Executes:

public function execute(){
Artisan::call('backup:mysql-dump');

My Question is How To Write Code for Executing Command

php artisan mysql-dump custom_file

**Comment by ibraah88** [comment]
up

**Comment by Dewbud** [comment]
You can pass parameters to programic artisan commands by passing an array as the second parameter.

```php
\Artisan::call('backup:mysql-dump', [
    'custom_file' => 'for_bar'
]);
```

[https://laravel.com/docs/master/artisan#programmatically-executing-commands](url)

**Comment by MadHack25** [comment]
Thank You Guys
it Worked! ))

**Comment by NazarAli** [comment]
i have same problem try the example and not work

**Comment by paulvl** [comment]
@NazarAli have you tried the proposed answer from @Dewbud on https://github.com/paulvl/backup/issues/21#issuecomment-388569153
