### ISSUE TITLE
Large size database dump storage to S3

### ISSUE THREAD

**Issue by annugaur2010** [paulvl/backup#28]
There is an issue when we are uploading large size (130M) database dump to S3. It is giving the following error:

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 157945856) (tried to allocate 847000680 bytes) in path/to/project/vendor/league/flysystem/src/Util/MimeType.php on line 28

**Comment by pvidal-vmc** [comment]
Has been happen 3 years from this but this issue is related to your server memory.

**Comment by paulvl** [comment]
Has been happen 3 years from this but this issue is related to your server memory.
