### ISSUE TITLE
Call to undefined function Backup\Console\Commands\ends_with()

### ISSUE THREAD

**Issue by slzno** [paulvl/backup#34]
![image](https://user-images.githubusercontent.com/44006503/75800180-c0aadc80-5d3e-11ea-9139-77142e84b175.png)

**Comment by paulvl** [comment]
Which laravel version are you using @ldavidsp ??

**Comment by slzno** [comment]
Laravel 7.x

**Comment by GodlikeBasic** [comment]
i use this solution for Laravel 7.x
You can pull them in with `composer require laravel/helpers`

https://github.com/laravel/nova-issues/issues/1905#issuecomment-648582996

**Comment by paulvl** [comment]
@ldavidsp fixed on new version 4.*

**Comment by slzno** [comment]
@paulvl Thanks you.
