### ISSUE TITLE
escapeshellcmd

### ISSUE THREAD

**Issue by crisp-github** [paulvl/backup#7]
Using the 5.1 branch the dumpCommand could use escapeshellcmd or spacial characters can break things (e.g. backpack in the password) e.g.

$dumpCommand = "mysqldump -e -f -h $host -u ".escapeshellcmd($username)." -p".escapeshellcmd($password)." ".escapeshellcmd($database)." > $backupPath$filename.sql";

**Comment by paulvl** [comment]
Fixed on version 3.*
Using escapeshellarg
